### ISSUE TITLE
Inclusion within isomorphic git

### ISSUE THREAD

**Issue by ChildishhAlbino** [adamziel/git-sparse-checkout-in-js#1]
Hello, I was hoping to discuss with you the ability to legally use or have you contribute this code back to the `isomorphic-git` repository itself.

There has been a [long standing request ](https://github.com/isomorphic-git/isomorphic-git/issues/1735) for `sparse-checkout` support within isomorphic-git but the original owner has left the project and no one seems to have picked up the mantle. I found this code entirely separate and thought it would serve as a good beginning point for an implementation.

Wondering if you have any thoughts about either opening up the license for someone like myself to include this code directly within isomorphic git or making the contribution yourself if you'd prefer.

**Comment by adamziel** [comment]
Hey @ChildishhAlbino! I'm happy for the code I wrote for this project to be used under the same MIT license as isomorphic-git. I won't be able to do the porting work myself, but I would be really happy to see a PR from you.

**Comment by ChildishhAlbino** [comment]
Thanks @adamziel - could I ask you update the license of this repository on Github per [this comment](https://github.com/isomorphic-git/isomorphic-git/issues/1735#issuecomment-2304503875) from one of the reviewers of `isomorphic-git`. 

I believe that's all I'd need to _legally_ be able to start a PR - hoping to get around to starting it next week sometime.

**Comment by mho22** [comment]
Fantastic @adamziel !

**Comment by adamziel** [comment]
License file added in https://github.com/adamziel/git-sparse-checkout-in-js/commit/e31059d9932614e1f0d87f8e2f170ccd4e50b370 :-) I also replied directly in https://github.com/isomorphic-git/isomorphic-git/issues/1735, let's close this issue and continue there.
